# fly.toml app configuration file generated for backend-misty-rain-4542 on 2024-09-25T10:33:43+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
# _DO NOT PUT SECRETS HERE_
# Secrets should be created via fly secrets

app = 'backend-misty-rain-4542'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
