/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WithJotaiImport } from './routes/with-jotai'
import { Route as TransactionsImport } from './routes/transactions'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WithJotaiRoute = WithJotaiImport.update({
  path: '/with-jotai',
  getParentRoute: () => rootRoute,
} as any)

const TransactionsRoute = TransactionsImport.update({
  path: '/transactions',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsImport
      parentRoute: typeof rootRoute
    }
    '/with-jotai': {
      id: '/with-jotai'
      path: '/with-jotai'
      fullPath: '/with-jotai'
      preLoaderRoute: typeof WithJotaiImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/transactions': typeof TransactionsRoute
  '/with-jotai': typeof WithJotaiRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/transactions': typeof TransactionsRoute
  '/with-jotai': typeof WithJotaiRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/transactions': typeof TransactionsRoute
  '/with-jotai': typeof WithJotaiRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/transactions' | '/with-jotai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/transactions' | '/with-jotai'
  id: '__root__' | '/' | '/transactions' | '/with-jotai'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TransactionsRoute: typeof TransactionsRoute
  WithJotaiRoute: typeof WithJotaiRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TransactionsRoute: TransactionsRoute,
  WithJotaiRoute: WithJotaiRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/transactions",
        "/with-jotai"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/transactions": {
      "filePath": "transactions.tsx"
    },
    "/with-jotai": {
      "filePath": "with-jotai.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
